# Dependencies
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Nonlinear Labyrinth
tagline:          ''
description:      'Reading notes and etc'
url:              http://monochoria.github.io

paginate:         5
